# Generated by Django 5.0.4 on 2025-04-26 14:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invitation_code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('vvip', 'VVIP'), ('vip', 'VIP'), ('reguler', 'Reguler')], default='reguler', max_length=8)),
                ('checkin', models.BooleanField(default=False)),
                ('checkin_at', models.DateTimeField(blank=True, null=True)),
                ('desk_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('screen_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='guests_gues_name_917223_idx'), models.Index(fields=['checkin'], name='guests_gues_checkin_e31691_idx')],
            },
        ),
    ]
