# Generated by Django 5.0.4 on 2025-06-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='detail',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
